# Generated by Django 4.0.6 on 2022-08-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(help_text='Назва кабінету', max_length=50)),
                ('cabinet_uk', models.CharField(help_text='Назва кабінету', max_length=50, null=True)),
                ('cabinet_en', models.CharField(help_text='Назва кабінету', max_length=50, null=True)),
                ('cabinet_pl', models.CharField(help_text='Назва кабінету', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінети',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Ім'я", max_length=20, verbose_name='Ім`я')),
                ('first_name_uk', models.CharField(blank=True, help_text="Ім'я", max_length=20, null=True, verbose_name='Ім`я')),
                ('first_name_en', models.CharField(blank=True, help_text="Ім'я", max_length=20, null=True, verbose_name='Ім`я')),
                ('first_name_pl', models.CharField(blank=True, help_text="Ім'я", max_length=20, null=True, verbose_name='Ім`я')),
                ('last_name', models.CharField(blank=True, help_text='Прізвище', max_length=20, verbose_name='Прізвище')),
                ('last_name_uk', models.CharField(blank=True, help_text='Прізвище', max_length=20, null=True, verbose_name='Прізвище')),
                ('last_name_en', models.CharField(blank=True, help_text='Прізвище', max_length=20, null=True, verbose_name='Прізвище')),
                ('last_name_pl', models.CharField(blank=True, help_text='Прізвище', max_length=20, null=True, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, help_text="Ім'я по батькові", max_length=20, verbose_name='По батькові')),
                ('middle_name_uk', models.CharField(blank=True, help_text="Ім'я по батькові", max_length=20, null=True, verbose_name='По батькові')),
                ('middle_name_en', models.CharField(blank=True, help_text="Ім'я по батькові", max_length=20, null=True, verbose_name='По батькові')),
                ('middle_name_pl', models.CharField(blank=True, help_text="Ім'я по батькові", max_length=20, null=True, verbose_name='По батькові')),
                ('speciality', models.CharField(blank=True, help_text='Спеціалізація', max_length=20, verbose_name='Спеціальність')),
                ('speciality_uk', models.CharField(blank=True, help_text='Спеціалізація', max_length=20, null=True, verbose_name='Спеціальність')),
                ('speciality_en', models.CharField(blank=True, help_text='Спеціалізація', max_length=20, null=True, verbose_name='Спеціальність')),
                ('speciality_pl', models.CharField(blank=True, help_text='Спеціалізація', max_length=20, null=True, verbose_name='Спеціальність')),
                ('description', models.TextField(blank=True, help_text='Опис спеціаліста', verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, help_text='Опис спеціаліста', null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, help_text='Опис спеціаліста', null=True, verbose_name='Опис')),
                ('description_pl', models.TextField(blank=True, help_text='Опис спеціаліста', null=True, verbose_name='Опис')),
                ('image', models.URLField(blank=True, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Спеціаліст',
                'verbose_name_plural': 'Спеціалісти',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='РРРР-МММ-ДД')),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '11:00 - 13:00'), (2, '15:00 - 17:00')])),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_last_name', models.CharField(max_length=60)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist_app.location')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist_app.specialist')),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Записи на прийом',
            },
        ),
    ]
