# Generated by Django 4.0.6 on 2022-08-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist_app', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created'], 'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарії'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_specialist', to='Specialist_app.specialist'),
        ),
    ]
