# Generated by Django 4.0.6 on 2022-07-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Ім'я", max_length=20)),
                ('last_name', models.CharField(help_text='Прізвище', max_length=20)),
                ('middle_name', models.CharField(help_text="Ім'я по батькові", max_length=20)),
                ('speciality', models.CharField(help_text='Спеціалізація', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='РРРР-МММ-ДД')),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')])),
                ('patient_name', models.CharField(max_length=60)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'timeslot')},
            },
        ),
    ]
