# Generated by Django 4.0.6 on 2022-07-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.schedule'),
        ),
    ]
