# Generated by Django 4.0.6 on 2022-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0002_schedule_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')]),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
