# Generated by Django 4.0.6 on 2022-07-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0003_alter_appointment_timeslot_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')])),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.schedule'),
            preserve_default=False,
        ),
    ]
