# Generated by Django 4.0.6 on 2022-07-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0004_schedule_appointment_time_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_list',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.schedule'),
        ),
    ]
