# Generated by Django 4.0.6 on 2022-07-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0005_remove_appointment_time_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Doctor_app.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timeslot',
            field=models.IntegerField(),
        ),
    ]
