# Generated by Django 4.0.6 on 2022-07-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0006_alter_appointment_timeslot_alter_schedule_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')]),
        ),
    ]
