# Generated by Django 4.0.6 on 2022-07-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0007_alter_appointment_timeslot_alter_schedule_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(help_text='Назва кабінету', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_last_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '08:00 - 10:00'), (1, '17:00 - 20:00')]),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cabinet',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor_app.location'),
            preserve_default=False,
        ),
    ]
