# Generated by Django 4.0.6 on 2022-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0008_location_appointment_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, help_text='Опис спеціаліста'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialist_template',
            field=models.URLField(blank=True),
        ),
    ]
