# Generated by Django 4.0.6 on 2022-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0009_doctor_description_doctor_specialist_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Назва'),
            preserve_default=False,
        ),
    ]
